podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {
        stage('Build nginx docker image') {
            container('docker') {
                    dir('/nginx_config/') {
                nginx = docker.build("nginx/test", "-f nginx_config/Dockerfile . ")
               }
            }
        }        
    }
}
