   environment {
     imagename   = "nginx/test"
     dockerImage = ''
   }

podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {
        stage('Clone repository') {
            container('git') {
                sh 'whoami'
                sh 'hostname -i'
                sh 'git clone -b master https://github.com/palmapalermo/test-repo.git'
            }
        }

         stage('build nginx docker') {
             container('docker') {
                dir('test-repo/') {
                    sh  "docker build -t nginx/test ."
            }
         }
      }        
   }
}
