   environment {
     imagename   = "nginx/test"
     dockerImage = ''
   }

podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {
          container('docker') {
                   stage('clone image repo') {
                      git clone "https://github.com/palmapalermo/test-repo.git"
                      sh "ls -halr"
                   }
                   stage('build nginx docker') {
                          sh "ls -halr"
                          
                          script {
                          nginx = docker.build("nginx/test")
            }
         }
      }        
   }
}
